### ISSUE TITLE
Can't download gpt4all

### ISSUE THREAD

**Issue by guguxh** [mak448a/AI-Drawing-ChatBot#53] opened 2023-06-21 22:38 UTC
**Describe the bug**
Can't full download gpt4all

**To Reproduce**
Just download it by putting GPT4ALL in config and starting main.py

**Screenshots**
![image](https://github.com/mak448a/AI-Drawing-ChatBot/assets/61206153/1a91ac9d-7462-4cc8-ab37-de4a99cd1a21)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - Python Version: 3.10.9 

**Additional context**

**Comment by mak448a** [comment] 2023-06-21 22:47
Cannot reproduce on Linux. I'll check on Windows.

**Comment by mak448a** [comment] 2023-06-21 22:57
Cannot reproduce on Windows or Linux. Try going to `C:\Users\YourUsername\.cache\gpt4all` and deleting everything in that directory.

**Comment by guguxh** [comment] 2023-06-21 23:00
> Cannot reproduce on Windows or Linux. Try going to `C:\Users\YourUsername\.cache\gpt4all` and deleting everything in that directory and then try again.

Already done, this error continue

**Comment by mak448a** [comment] 2023-06-21 23:01
Hmm.... Can you visit gpt4all.io on your web browser?

**Comment by guguxh** [comment] 2023-06-21 23:06
> Hmm.... Can you visit https://gpt4all.io on your web browser? It might be a problem with your network.

Yes, I can

**Comment by mak448a** [comment] 2023-06-21 23:10
I don't know, try visiting the official GPT4All repository https://github.com/nomic-ai/gpt4all and ask there

**Comment by mak448a** [comment] 2023-06-22 20:45
@gugxh Try downloading https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin and sticking it in `C:\Users\YourUsername\.cache\gpt4all

**Comment by guguxh** [comment] 2023-06-23 04:22
> @guguxh Try downloading https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin and sticking it in `C:\Users\YourUsername.cache\gpt4all

the issue is about the version of gpt4all, I recommend you to update the package version also

**Comment by mak448a** [comment] 2023-06-28 01:34
Closing as I don't think this has to do with my code.

**Closed by mak448a** 2023-06-28 01:34 UTC
Labels: bug
